version: "3.4"
services:
  frontend:
    image: node:19.8.1-bullseye
    container_name: frontend
    entrypoint: "/bin/entrypoint.sh" 
    ports:
      - 8000:8000
    working_dir: /src/app
    volumes:
      - type: bind
        source: ./frontend/entrypoint.sh
        target: /bin/entrypoint.sh
      - type: bind
        source: ../frontend
        target: /src/app
    depends_on:
      - backend 
  backend:
    # image: python:3.9.16-bullseye
    build:
      dockerfile: ./backend/Dockerfile
    container_name: backend 
    entrypoint: "/bin/entrypoint.sh" 
    env_file:
      - .dev_db.env
    environment:
      - PORT=3000
      - DJANGO_SECRET_KEY=/run/secrets/db-password
      - ENV=DEV
      - PIP_DISABLE_PIP_VERSION_CHECK=1
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - 3000:3000
    secrets:
      - django-secret
    working_dir: /src/app
    volumes:
      - type: bind
        source: ./backend/entrypoint.sh
        target: /bin/entrypoint.sh
      - type: bind
        source: ../backend
        target: /src/app
      # Used for vscode
      # - type: bind
      #   source: ./.python-site-packages
      #   target: /python-site-packages
    depends_on:
      - db
  db:
    image: postgres:15.2-alpine3.17
    container_name: db
    env_file:
      - .dev_db.env
    ports:
      - 5432:5432
    secrets:
      - db-password
    restart: always
    volumes:
      - type: volume
        source: db 
        target: /var/lib/postgresql/data/

volumes:
  db:
secrets:
  db-password:
    file: ../.secrets/db-password.secret
  django-secret:
    file: ../.secrets/django.secret